# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_websitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='descript',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='favicon',
            field=models.FileField(default=1, upload_to=utils.get_file_path),
            preserve_default=False,
        ),
    ]
