# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170413_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='descript',
            field=models.TextField(),
        ),
    ]
